// Generated by LiveScript 1.3.1
(function(){
  var root, addlog, mkrecognition;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  addlog = function(text){
    console.log(text);
    return $('<div>').text(text).appendTo('#results');
  };
  mkrecognition = function(){
    var recognition;
    root.recognition = recognition = new webkitSpeechRecognition();
    recognition.lang = 'en-US';
    recognition.continuous = false;
    recognition.interimResults = false;
    recognition.maxAlternatives = 5;
    recognition.onresult = function(event){
      var i$, ref$, len$, x;
      addlog(event);
      addlog(event.results.length);
      addlog(event.results[0].length);
      for (i$ = 0, len$ = (ref$ = event.results[0]).length; i$ < len$; ++i$) {
        x = ref$[i$];
        addlog(x.transcript + '|' + x.confidence);
      }
      if (event.results[0].isFinal) {
        addlog('done');
        recognition.stop();
        return $('#startbutton').text('Press me');
      }
    };
    return recognition;
  };
  $(document).ready(function(){
    var recognition;
    recognition = mkrecognition();
    return $('#startbutton').click(function(){
      console.log('started!');
      $('#startbutton').text('Recording');
      return recognition.start();
    });
  });
}).call(this);
